title: EDM Portfolio of L. Turla
logo: ![pfp](1742064055110.jpg)
show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
